using Godot;
using System.Collections.Generic;
using System.Threading.Tasks;

public partial class ITBall : Node2D
{
	private enum NpcType { None, AppDeveloper, ProjectLead }
	private Area2D _appDevArea; private Area2D _leadArea; private Label _promptLabel; private Label _statusLabel; private Button _finishButton; private CharacterBody2D _player; private DialogueBoxUI _dialogueUi; private bool _dialogueOpen; private NpcType _nearNpc=NpcType.None; private bool _appDevDone; private bool _leadDone;
	public override void _Ready(){StatusOverlay.AttachTo(this,false);_appDevArea=GetNode<Area2D>("ITBallAppDeveloperNPC/InteractionArea");_leadArea=GetNode<Area2D>("ITBallProjectLeadNPC/InteractionArea");_player=GetNodeOrNull<CharacterBody2D>("Player");_promptLabel=GetNode<Label>("UI/InteractPromptLabel");_statusLabel=GetNode<Label>("UI/DialoguePanel/ContentContainer/StatusLabel");_finishButton=GetNode<Button>("UI/DialoguePanel/ContentContainer/ActionRow/FinishEventButton");_dialogueUi=GD.Load<PackedScene>("res://scenes/UI/Dialogue/dialogue_box.tscn").Instantiate<DialogueBoxUI>();AddChild(_dialogueUi);_appDevArea.BodyEntered+=_=>_nearNpc=NpcType.AppDeveloper;_appDevArea.BodyExited+=_=>{if(_nearNpc==NpcType.AppDeveloper)_nearNpc=NpcType.None;};_leadArea.BodyEntered+=_=>_nearNpc=NpcType.ProjectLead;_leadArea.BodyExited+=_=>{if(_nearNpc==NpcType.ProjectLead)_nearNpc=NpcType.None;};_finishButton.Pressed+=OnFinishEventPressed;GlobalVars.Instance.ITBallGoodChoices=0;_finishButton.Disabled=true;_promptLabel.Visible=false;_statusLabel.Text="Talk to both developers before finishing the event.";}
	public override void _Process(double d){_promptLabel.Visible=!_dialogueOpen&&_nearNpc!=NpcType.None;if(_promptLabel.Visible)_promptLabel.Text="Press E to talk";}
	public override void _UnhandledInput(InputEvent e){if(!_dialogueOpen&&e.IsActionPressed("interact")){if(_nearNpc==NpcType.AppDeveloper)_=OpenAppAsync();if(_nearNpc==NpcType.ProjectLead)_=OpenLeadAsync();}}
	private async Task OpenAppAsync(){if(_appDevDone){await _dialogueUi.ShowLineAsync("App Developer","We already talked.");_dialogueUi.HideAll();return;}await RunDialogueAsync("App Developer","We're building a student productivity app, but we need someone reliable. What can you contribute?",new List<string>{"I've been practicing consistently, fixing bugs, and building my portfolio. I can help implement and test features.","I'm still learning, but I'm willing to take small tasks and improve.","I mostly want to join if it makes money quickly."},i=>{var s=GlobalVars.Instance;if(i==0){s.Attributes.IncreasePortfolio(10);s.Attributes.IncreaseNetworking(10);s.Attributes.IncreaseConfidence(5);s.ITBallGoodChoices+=1;}else if(i==1){s.Attributes.IncreasePortfolio(3);s.Attributes.IncreaseNetworking(5);s.Attributes.IncreaseConfidence(2);}else{s.Attributes.DecreaseConfidence(5);s.Attributes.DecreaseNetworking(5);}return "You finished talking with the app developer.";});_appDevDone=true;if(_appDevDone&&_leadDone)_finishButton.Disabled=false;}
	private async Task OpenLeadAsync(){if(_leadDone){await _dialogueUi.ShowLineAsync("Project Lead","We already talked.");_dialogueUi.HideAll();return;}await RunDialogueAsync("Project Lead","We need someone who can work with others and finish what they start. Why should we trust you?",new List<string>{"I've been rebuilding discipline this week. I know I still have a lot to learn, but I can communicate, show up, and deliver small features.","I can try, but I might need help staying on track.","I prefer working alone and I don't like feedback."},i=>{var s=GlobalVars.Instance;if(i==0){s.Attributes.IncreasePortfolio(10);s.Attributes.IncreaseNetworking(10);s.Attributes.IncreaseConfidence(5);s.ITBallGoodChoices+=1;}else if(i==1){s.Attributes.IncreaseConfidence(2);s.Attributes.IncreaseNetworking(3);}else{s.Attributes.DecreaseConfidence(5);s.Attributes.DecreaseNetworking(5);}return "You finished talking with the project lead.";});_leadDone=true;if(_appDevDone&&_leadDone)_finishButton.Disabled=false;}
	private async Task RunDialogueAsync(string npc,string prompt,List<string> choices,System.Func<int,string> apply){_dialogueOpen=true;SetPlayerControl(false);await _dialogueUi.ShowLineAsync(npc,prompt);int idx=await _dialogueUi.ShowChoicesAsync(choices);await _dialogueUi.ShowLineAsync("You",choices[idx]);_statusLabel.Text=apply(idx);await _dialogueUi.ShowLineAsync(npc,_statusLabel.Text);_dialogueUi.HideAll();_dialogueOpen=false;SetPlayerControl(true);}
	private void SetPlayerControl(bool enabled){if(_player!=null)_player.SetPhysicsProcess(enabled);}
	private void OnFinishEventPressed(){var s=GlobalVars.Instance;bool goodDialogue=s.ITBallGoodChoices>=2;bool skillReady=s.Attributes.Knowledge>=60;bool portfolioReady=s.Attributes.Portfolio>=40;bool confidenceReady=s.Attributes.Confidence>=40;bool networkingReady=s.Attributes.Networking>=30;if(goodDialogue&&skillReady&&portfolioReady&&confidenceReady&&networkingReady){s.JoinedDeveloperGroup=true;_statusLabel.Text="The developer group is impressed. They invite you to join their app project.";s.ShowReaction("This could become something bigger than just finding a job.");}else if(goodDialogue){s.JoinedDeveloperGroup=false;_statusLabel.Text="You made a good impression, but you need stronger skills and portfolio work before joining the project.";s.ShowReaction("I'm close. I need to keep building my skills.");}else{s.JoinedDeveloperGroup=false;_statusLabel.Text="The developers decide you are not ready for the project yet.";s.ShowReaction("That stings, but I can still turn this around.");}TransitionManager.Instance?.ChangeSceneToFileWithFade("res://scenes/Domitory/dormitory.tscn");}
}
